/**
 * EHierarchyParameterType
 * @enum
 */
export enum EHierarchyParameterType {
    VoiceVolume,
    VoicePitch = 0x02,
    VoiceLowPass = 0x03,
    VoiceHighPass = 0x04,
    BusVolume = 0x05,
    MakeUpGain = 0x06,
    PlaybackPriority = 0x07,
    PlaybackPriorityOffset = 0x08,
    MotionToVolumeOffset = 0x09,
    MotionLowPass = 0x1,
    PositioningPannerX = 0x0C,
    PositioningPannerY,
    PositioningCenterPercentage,
    ActionDelay,
    ActionFadeInTime,
    Probability,
    OverrideAuxBus0Volume = 0x13,
    OverrideAuxBus1Volume,
    OverrideAuxBus2Volume,
    OverrideAuxBus3Volume,
    GameDefinedAuxSendVolume,
    OverrideBusVolume,
    OverrideBusHighPassFilter,
    OverrideBusLowPassFilter,
    HdrThreshold,
    HdrRatio,
    HdrReleaseTime,
    HdrOutputGameParam,
    HdrOutputGameParamMin,
    HdrOutputGameParamMax,
    HdrEnvelopeActiveRange,
    MidiNoteTrackingUnknown = 0x2E,
    MidiTranspositionInt,
    MidiVelocityOffsetInt,
    MidiFiltersKeyRangeMin,
    MidiFiltersKeyRangeMax,
    MidiFiltersVelocityRangeMin,
    MidiFiltersVelocityRangeMax,
    PlaybackSpeed = 0x36,
    MidiClipTempoSourceIsFile,
    LoopTimeUInt = 0x3A,
    InitialDelay
}